// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://heulgjoubeyxyrusaulf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhldWxnam91YmV5eHlydXNhdWxmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzNzc4MDIsImV4cCI6MjA2Nzk1MzgwMn0.AG9Q31Rl1nfQnoRUqtw90LiKZA3eaKjQoD7cePw9fxQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});